# -*- coding: utf-8 -*-
"""first_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y5ptHAjAtgMxBUtKLyfHQGiAVpXoGLle

## _Isso é um texto em **Markdown**_

<h1>Isso é um texto em <b>HTML<b><h1>
"""

print("Isto é uma linha de código em Python\n")

"""<bottom type="buttom">Clique aqui</input>"""